import "regenerator-runtime/runtime";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import AiBot from "@/components/AiChatBot/AiBot";

// Provider
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Clinca San Miguel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body className="font-inter bg-[#F8F5F0] relative overflow-x-hidden w-[100vw]">
        <Providers>
          <article className="h-[43px] w-full bg-[#19192C] flex justify-center items-center text-[12px] sm:text-[16px] text-center text-[#F8F5F0]">
            Select language from the dropdown on the right corner{" "}
          </article>
          <Navbar />
          {children}

          <Footer />
          <div
            className="sticky z-[999999] bottom-10 right-10"
            style={{ zIndex: 999999 }}
          >
            <AiBot />
          </div>
        </Providers>
      </body>
    </html>
  );
}
