import "regenerator-runtime/runtime";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";

// Provider
import { Providers } from "../providers";
import AiBotMain from "@/components/AiChatBot/AiBotMain";

import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Clinca San Miguel",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale: any) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html
      lang={locale}
      dir={dir(locale)}
      className={`${inter.variable} ${poppins.variable}`}
    >
      <body className="font-inter bg-[#F8F5F0] relative overflow-x-hidden w-[100vw]">
        <Providers>
          <article className="h-[43px] w-full bg-[#19192C] flex justify-center items-center text-[12px] sm:text-[16px] text-center text-[#F8F5F0]">
            Select language from the dropdown on the right corner
          </article>
          <Navbar />
          {children}

          <Footer />
          <div
            className="sticky z-[999999] bottom-10 right-10"
            style={{ zIndex: 999999 }}
          >
            <AiBotMain />
          </div>
        </Providers>
      </body>
    </html>
  );
}
